### ISSUE TITLE
Fatal error during upgrade or activation

### ISSUE THREAD

**Issue by grab76** [dorzki/Slack-Notifications#11]
Hi,

Since the latest version, the plugin doesn't work.

This is the error : 

"Parse error: syntax error, unexpected '.', expecting ',' or ';' in /wordpress/wp-content/plugins/dorzki-notifications-to-slack/core/notifications/notification-type.php on line 33"

**Comment by dorzki** [comment]
Hi @grab76 ,
I'm sorry to here that, can you please send me login details to your server so i can see what the issue is and to fix it?

Send me via email and not here please.

**Comment by dorzki** [comment]
Hi @grab76,
The issue is now resolved (#12).

**Comment by grab76** [comment]
Hi @dorzki 

Thank you for the quick fix.
Glad to have contributed.

**Comment by dorzki** [comment]
@grab76 I'm glad to hear it works now, thanks for reporting the issue 👍
