### ISSUE TITLE
Parse Error in 2.0

### ISSUE THREAD

**Issue by mahype** [dorzki/Slack-Notifications#14]
Hello and thank you for the great plugin! :)

There is a syntax error in the new version:

Parse error: syntax error, unexpected '.', expecting ',' or ';' in /wp-content/plugins/dorzki-notifications-to-slack/core/notifications/notification-type.php on line 33

**Comment by dorzki** [comment]
Hi @mahype,
The issue was fixed on version 2.0.1.

Please update your plugin.

**Comment by mahype** [comment]
I have already installed 2.0.1

**Comment by dorzki** [comment]
What version of PHP does your server run?
Also, please paste here the value of `slack_notifications` from `wp_options`.

**Comment by mahype** [comment]
It is also in 2.0.1:
https://github.com/dorzki/Slack-Notifications/blob/master/core/notifications/notification-type.php#L33

It's the same server constellation as in ticket #15 

This is the value in the wp_options:
`[{"type":"system","action":"wordpress_update","channel":null,"title":"[System] WordPress Update Available"},{"type":"system","action":"plugins_update","channel":null,"title":"[System] WordPress Update Available"},{"type":"system","action":"themes_update","channel":null,"title":"[System] Theme Update Available"},{"type":"user","action":"new_user","channel":null,"title":"[Users] User Registered"},{"type":"comment","action":"new_comment","channel":null,"title":"[Comments] New Comment"},{"type":"post","action":"new_post","channel":null,"title":"[Posts] Post Published"},{"type":"post","action":"update_post","channel":null,"title":"[Posts] Post Updated"},{"type":"page","action":"new_page","channel":null,"title":"[Pages] Page Published"},{"type":"page","action":"update_page","channel":null,"title":"[Pages] Page Updated"}]`

**Comment by dorzki** [comment]
Ok,
Now i see the issue.

Fixing it now.

**Comment by dorzki** [comment]
Hi @mahype,
I've deployed an update, would love if you can test it before i'm pushing it to WordPress repo.
