### ISSUE TITLE
Fatal Error in version 2.0

### ISSUE THREAD

**Issue by mahype** [dorzki/Slack-Notifications#15]
Here it is!

Fatal error: Can't use method return value in write context in /wp-content/plugins/dorzki-notifications-to-slack/core/notifications/woocommerce.php on line 355

**Comment by mahype** [comment]
Can you please add the Pull Request #16, because the acutal version is occuring massive errors to existing sites which updating to it? :)

**Comment by dorzki** [comment]
Hi @mahype ,
What is your:

WordPress version
WooCommerce version
PHP version

**Comment by mahype** [comment]
### WordPress Environment ###

WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.4.27
PHP Version: 7.0.20
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.55.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.6.19
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

**Comment by dorzki** [comment]
Thanks,
Looking into it.

**Comment by dorzki** [comment]
Hi @mahype,
I've deployed an update, would love if you can test it before i'm pushing it to WordPress repo.
