### ISSUE TITLE
Client IP should be replaced with value from X-Forwarded-For header if present

### ISSUE THREAD

**Issue by cpdk** [dorzki/Slack-Notifications#25]
We are running the plugin in a setup where WordPress is behind a CDN (AWS CloudFront) and a LoadBalancer (AWS ALB). Both of which will terminate SSL (and thus TCP) - therefor the real client IP is not visible except as an HTTP Header. 

What we see on slack is the internal IP of the LoadBalancer (in the 10.0.0.0/8 non-public range): 

Most proxies (and all we use) handle this by following RFC 7239 - ie. by injecting an HTTP header called X-Forwarded-For with a list of IPs. 

See: [the RFC - section 5.2](https://tools.ietf.org/html/rfc7239#section-5.2) for details

It would be great if this otherwise great plugin could pickup if the user is accessing WordPress through a proxy and then pickup the actual client IP to post to Slack.

**Comment by dorzki** [comment]
Hi @cpdk ,
I will release a hotfix in a few days.

Thanks for reporting the bug!

**Comment by dorzki** [comment]
Hi @cpdk,
I've fixed the issue on commit 280c5b2135f363af2205921d9ab29804dee10ffa.

The version will be uploaded to WordPress Repo soon.

**Comment by cpdk** [comment]
Sound great - will test asap

**Comment by dorzki** [comment]
@cpdk Cool, would love to get an update if the issue was resolved.

Also, if you can rate the plugin it would be awesome :)
