### ISSUE TITLE
Spam Filter For Comments: Only get notified by new comments which aren't marked as spam

### ISSUE THREAD

**Issue by yapes91** [dorzki/Slack-Notifications#26]
Currently Slack notifications is sending notifications whenever a new comments comes in. 

I'd love a filter, where only notifications from approved (non spam) comments get send to Slack. 

Is that possible?

**Comment by dorzki** [comment]
Hi @yapes91 ,
I Will release a hotfix in a few days.

**Comment by dorzki** [comment]
Hi @yapes91 ,
I've fixed the issue on commit d8526120ddf532660f1b8441f266bd8e8dc3e46d.

The version will be uploaded to WordPress Repo soon.
