### ISSUE TITLE
WooCommerce error

### ISSUE THREAD

**Issue by keurigonline** [dorzki/Slack-Notifications#31]
When changing order status I get this error:

`PHP Fatal error:  Uncaught Error: Call to a member function get_name() on boolean in /srv/users/wordpress/apps/wordpress/public/wp-content/plugins/dorzki-notifications-to-slack/core/notifications/woocommerce.php:175
Stack trace:
#0 /srv/users/wordpress/apps/wordpress/public/wp-content/plugins/dorzki-notifications-to-slack/core/notifications/woocommerce.php(244): SlackNotifications\Notifications\WooCommerce->build_order_attachments(Object(WC_Order))
#1 /srv/users/wordpress/apps/wordpress/public/wp-includes/class-wp-hook.php(288): SlackNotifications\Notifications\WooCommerce->order_transition(7682)
#2 /srv/users/wordpress/apps/wordpress/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /srv/users/wordpress/apps/wordpress/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /srv/users/wordpress/apps/wordpress/public/wp-content/plugins/woocommerce/includes/class-wc-order.php(327): do_action('woocommerce_ord...', 7682, Object(WC_Order))
#5 /srv/users/wordpress/apps/wordpress/public/wp-content/plugins/woocommerce/inc in /srv/users/wordpress/apps/wordpress/public/wp-content/plugins/dorzki-notifications-to-slack/core/notifications/woocommerce.php on line 175`

**Comment by dorzki** [comment]
Hi @keurigonline,
Could you please go do "Support" tab and copy both reports please?

**Comment by dorzki** [comment]
Hi @keurigonline,
I've tested this issue several times and i can't seem to see the error you are talking about.

In order for me to checks and verify this issue I need you to copy both reports under "Support" page.
