### ISSUE TITLE
Contact form 7 Notification 

### ISSUE THREAD

**Issue by YuvrajKhavad** [dorzki/Slack-Notifications#34]
Hello @dorzki 
There are no any issues but a new feature request and thanks for great plugin.

Add contact form 7 plugin to this plugin for notification. When anyone sends a message using contact form 7 give the option to sent notification on the slack channel.

Thank You
Yuvraj

**Comment by dorzki** [comment]
Hi @YuvrajKhavad,
I'm glad to hear you enjoy the plugin! :)

What kind of notifications do you want for CF7?

**Comment by YuvrajKhavad** [comment]
Hello @dorzki,
Thanks for replay.
You can just send a simple message like "There is a new message through **Contact form 1**".
CF7 have a dynamic form so sending fillup data to slack is not good solutions, the Simple message also work.

Thanks

**Comment by dorzki** [comment]
Ok, i will look into it.

**Comment by mtruitt** [comment]
I'm wondering the application of this as CF7 sends emails

**Comment by itaiarbel** [comment]
hi all... i just created a cf7 class for slack notifications,
with [form submitted], [form created], [form updated] evens...
 you can get it on:
Add this class file (the class itself):   
https://github.com/itaiarbel/Slack-Notifications/blob/master/core/notifications/cf7.php
You  also needto init the class in:
https://github.com/itaiarbel/Slack-Notifications/blob/master/core/plugin.php

**Comment by dorzki** [comment]
@itaiarbel if you would like to contribute the code, please make PR.

**Comment by itaiarbel** [comment]
pull request created...
