### ISSUE TITLE
Is it possible to have multiple  Webhook URL?

### ISSUE THREAD

**Issue by Anasxrt** [dorzki/Slack-Notifications#35]
Hi @dorzki 
Currently it only can integrate with single Webhook URL. But normally on difference Slack channel it will be difference Webhook URL. I saw when we add new notification in plugin, it able to post to different channel.

I wonder how we can get it post to different channel with single Webhook URL. Do I missing something?

Also, I have create Slack App instead of Legacy Slack incoming webhook. If you can have difference approach to integrate slack instead of using Legacy Webhook, it may using Slack App integration as well. It more powerful.

Regards,

**Comment by dorzki** [comment]
Hello @Anasxrt,
Why do you need a different webhooks? Do you want use several Slack accounts?

If you would like to use several channels under the same account you can do it with a single webhook.

About the approach, the plugin needs to be as simple as possible, I believe that creating a new application will be difficult for basic users.

**Comment by Anasxrt** [comment]
Hi @dorzki 

"If you would like to use several channels under the same account you can do it with a single webhook."

refer to the quoted, that the problem that I can't get it done on simple webhook. Could you lead me of how to?

Regards,

**Comment by dorzki** [comment]
When you create as simple webhook, you will get a link, copy this link and paste it in the field on the plugin settings.

Then, when you edit a notification, you will have a field named "Channel", you can simply paste there the name of the channel you would like it to send to.
