### ISSUE TITLE
Updated CPT notification sent without setup

### ISSUE THREAD

**Issue by jphorn** [dorzki/Slack-Notifications#37]
Hi,

Thanks for the great plugin. I seem to have a rather weird issue with the difference between `post` posts and custom post type posts. I have configured notifications for 'Post Pending' (and 'Post Scheduled') and have the same for every CPT configured for our site (over 10). However; when I **update** any custom post type post, the Update notification is being sent to Slack, without it actually being configured in the plugin settings. This doesn't happen for the `post` post type, but affects every other (custom) post type.

Any clue?

![2018-10-01_23-07-14](https://user-images.githubusercontent.com/478156/46315939-0655f980-c5cf-11e8-956c-ca6727388e7a.png)

![2018-10-01_23-10-04](https://user-images.githubusercontent.com/478156/46315995-31d8e400-c5cf-11e8-8bf6-4e387ec1db2c.png)

**Comment by dorzki** [comment]
Hi @jphorn,
Can you go to the plugin support page and paste here both of the textarea contents?

**Comment by jphorn** [comment]
I'd rather not send that publicly. Is there a way to send this privately?

**Comment by dorzki** [comment]
Sure, please send it to my mailbox webmaster AT dorzki.co.il

**Comment by dorzki** [comment]
Hi @jphorn,
I've released a new version which addresses this issue.

Sorry for the long wait.
