### ISSUE TITLE
Author in Slack always creator of page

### ISSUE THREAD

**Issue by zenith4237** [dorzki/Slack-Notifications#39]
I noticed that the UpdateBot always shows the original author of a page below "Updated By" no matter who updated the page. Is there a way to change this to always display the user that is the author of the current revision, the one that made the change?

Greetings

**Comment by dorzki** [comment]
Hi @zenith4237,
Thanks for reporting, i will investigate and issue a new version soon.

**Comment by dorzki** [comment]
It is fixed in release v2.0.5
