### ISSUE TITLE
Product informations no more added to slack message (v2.0.6)

### ISSUE THREAD

**Issue by caudurieauelma** [dorzki/Slack-Notifications#41]
Hi,
I upgrade the plugin to v2.0.6 and since this update, informations about order are not added to slack message anymore.

I compare both versions (the old and the current) [source](https://github.com/dorzki/Slack-Notifications/compare/v2.0.5...v2.0.6). I didn't find the issue (I'm not a Wordpress dev so...).

My current version of WooCommerce is 3.8.1 and some other plugins related to WooCommerce. Tell me if you need them to debug.

Previous version (v2.0.5 today at 4:27PM):
> There is a new order on Box!
> 
> Order ID
> 8194
> Order Status
> Pending
> Order Total
> 22,80€
> Paid Via
> Carte de paiement (Stripe)
> 
> Product Name
> Box Décembre 2019 x1

New version (v2.0.6 today at 5:55PM):
> There is a new order on Box!
> 
> Order ID
> 8202
> Order Status
> Pending
> Order Total
> 59,70€
> Paid Via
> Carte de paiement (Stripe)

Thanks you for your future update ;)

**Comment by dorzki** [comment]
Hi @caudurieauelma,
Thanks for reporting, I'll check and get back to you.

**Comment by dorzki** [comment]
I've issued a new version which addresses this issue. (v2.0.7)

**Comment by caudurieauelma** [comment]
Perfect, you fixed the issue ;)

**Comment by dorzki** [comment]
@caudurieauelma
No problem, thanks for reporting :)

If you are fluent in a language besides then English, It would be awesome if you could contribute by helping translate the plugin :)

**Comment by caudurieauelma** [comment]
Will think about that ;).
I'm fluent in French (native).

**Comment by dorzki** [comment]
@caudurieauelma That would be awesome if you agree :)

Thanks for using my plugin :)

**Comment by caudurieauelma** [comment]
Hi dorzki,
Happy new year ;).
Can you provide me a file with your plugin translations? You can send it to my email ;)

**Comment by dorzki** [comment]
Hi @caudurieauelma,
Happy new year to you too :)

Do you have WordPress.org account?

**Comment by caudurieauelma** [comment]
No I don't sorry. I installed WordPress on my server but nothing else. My brother plugged plugins, write posts... He asks my help only when he has big issues (in WordPress core). So I don't have an account. I prefer to do not have one, if possible.

**Comment by dorzki** [comment]
That's ok, i need someone with a wordpress.org account in order to maintain the translation.
Thanks anyway, much appreciated :)
