### ISSUE TITLE
Changing the namespace broke customisations

### ISSUE THREAD

**Issue by grappler** [dorzki/Slack-Notifications#42]
Changing the namespace in https://github.com/dorzki/Slack-Notifications/commit/81aaaf0b0f0c33af7ec7107a97a10ca5bafe822a was a breaking change and should have been documented as such in the readme.

We were using the class to create a custom notification type.

```
use Slack_Notifications\Notifications\Notification_Type;

/**
 * Class used to register a custom notification type for the job board.
 *
 * @link https://github.com/dorzki/Slack-Notifications/blob/master/core/notifications/class-notification-type.php
 */
class JobBoard extends Notification_Type {}
```

**Comment by dorzki** [comment]
Hi @grappler,
You are correct, i've forgot to write about it and/or add compatibility notice.

Please excuse me :)
