### ISSUE TITLE
Struggling to find a way to fire the 'send_message' function manually

### ISSUE THREAD

**Issue by adamcollingburn** [dorzki/Slack-Notifications#46]
As above, I'd like to be able to create my own slack messages from my custom functions but struggling to find a way to do this

**Comment by dorzki** [comment]
Hi Adam,
You can do something like that:

```
<?php 
$bot = Slack_Bot::get_instance();

$bot->send_message( $message, $attachments, $args );
```

**Comment by dorzki** [comment]
Hi Adam,
You can do something like that:

```php
Slack_Bot::get_instance()->send_message( $message, $attachments, $args );
```

**Comment by adamcollingburn** [comment]
Thanks Dorzki - I tried this and just get Class Slack_Bot could not be found

**Comment by adamcollingburn** [comment]
So I tried to include 'core/class-slack-bot.php' and it says the class is already in use 😅

**Comment by dorzki** [comment]
Don't forget to add the namespace at the top.of the file:

```php
use Slack_Notifications\Slack_Bot;
```

Or add the namespace before the class name:
```php
Slack_Notifications\Slack_Bot::get_instance()->send_message( $message, $attachments, $args );
```

**Comment by adamcollingburn** [comment]
Thanks!

Do you know why it'd always be posting to the default channel? I've tried 

['channel' => '#artists']
and
['channel' => 'artists']

in $args param and it still just posts to the default channel

**Comment by adamcollingburn** [comment]
@dorzki Any thoughts on this? Do I need to find a channel ID or something?

**Comment by adamcollingburn** [comment]
@DorZuberi Any idea?

**Comment by DorZuberi** [comment]
Hi @adamcollingburn ,
Sorry for the late reply, I'm a bit packed up at work.

About your question, Slack have changed the way Webhook works.
I will release soon an update to address this issue.

**Comment by adamcollingburn** [comment]
Okay thanks dude

**Comment by DorZuberi** [comment]
I'm closing this issue because the main question was answered.
You may open a new issue about the wrong channel.

**Comment by adamcollingburn** [comment]
Hey @DorZuberi, 

Are you any closer to releasing an update for the webhook issue?
