### ISSUE TITLE
Allow message customization

### ISSUE THREAD

**Issue by MidnightLightning** [dorzki/Slack-Notifications#9]
While being metal 🤘 all the time is fun and all, in a corporate setting it would be nice to have more control over how the notification messages themselves are phrased.

Could the message templates be moved to settings on the settings page, so that individual Wordpress instances can tailor the notification messages to fit their brand/personality?

**Comment by dorzki** [comment]
Hi @MidnightLightning ,
Thanks for the contribution, let me do several tests and i will see if everything is ok :)

Also keep in mind i'm working on a new version :)

**Comment by dorzki** [comment]
Hi @MidnightLightning,
Check out the new version i've uploaded :)
